config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  resources :users, only: [:index, :show, :create, :edit, :update]
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy]
  
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'search#search'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :profile_image, destroy: false
  
  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  
  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}  
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end  

  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      @user = User.where("#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]
  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    @books = Book.all
  end  

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
       redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	
	<tr>
		<th>Follow</th>
		<th><%= link_to "#{user.followings.count} フォロー" %></th>
	</tr>
		<tr>
		<th>Follower</th>
		<th><%= link_to "#{user.followers.count} フォロー" %></th>
	</tr>
	
</table>

<div class="row">
		<% if user == current_user %>
		<%= link_to 'Edit', edit_user_path(user), class: 'btn btn-success btn-block' %>
		<% else %>
		<%= link_to 'MyPage', user_path(current_user), class: 'btn btn-success btn-block' %>
		<% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_with model:@user, local: true do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<%= flash[:notice] %>
<div class="container"> 
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			
			<h2>New book</h2>
			<%= render 'books/form', book: @book %>
		</div>
		<div class="col-xs-9">
			<h2>Users</h2>
			<!--users一覧 -->
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
						<th></th>
						<th>follower</th>
						<th>follow</th
					</tr>
				</thead>
			
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name %></td>
						<td><%= link_to "Show", user_path(@user), class: "user_#{@user.id}" %></td>
						<td>
							<% unless current_user == user %>
							  <% if current_user.following?(user) %>
							    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
							      <%= hidden_field_tag :follow_id, user.id %>
							      <%= f.submit 'Unfollow', class: 'btn-sm btn-danger btn-block' %>
							    <% end %>
							  <% else %>
							    <%= form_for(current_user.relationships.build) do |f| %>
							      <%= hidden_field_tag :follow_id, user.id %>
							      <%= f.submit 'Follow', class: 'btn-sm btn-primary btn-block' %>
							    <% end %>
							  <% end %>
							<% end %>
						</td>
						<td><%= link_to "#{user.followings.count}" %></td>
						<td><%= link_to "#{user.followers.count}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<!--users一覧 -->
		</div>
	</div>	
</div> 

app/views/users/show.html.erb
<div class="container"> 
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>
			
      <div class="mt-30">
				<% unless current_user == @user %>
						<% if current_user.following?(@user) %>
						 	<%= form_for(current_user.relationships.find_by(follow_id: @user.id), html: { method: :delete }) do |f| %>
							<%= hidden_field_tag :follow_id, @user.id %>
							<%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
						<% end %>
						<% else %>
							<%= form_for(current_user.relationships.build) do |f| %>
							<%= hidden_field_tag :follow_id, @user.id %>
							<%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
						<% end %>
					<% end %>
				<% end %>	
	    </div>
			<h2>New book</h2>
			<%= render 'books/form', book: @book %>
	  </div>
		<div class="col-xs-9">
			<h2>Books</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>
	
				<tbody>
					<% @books.each do |book| %>
						<tr>
							<td>
								<%= link_to user_path(book.user) do %>
									<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
								<% end %>
							</td>
							<td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
							<td><%= book.body %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
			<!--books一覧 -->
		</div>
	</div>
</div>