config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  resources :users, only: [:index, :show, :create, :edit, :update]
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy]
  
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'search#search'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
	
	def self.search(search, word)
    if search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
      @book = Book.where("#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
	end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @post = User.all
    @post_comment = PostComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     redirect_to book_path(@book), notice: "You have created book successfully."
    else
     @books = Book.all
     render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
      redirect_to books_path
    end  
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  def self.search(search, word)
    if search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
      @book = Book.where("#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end  
  
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end  

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<ol>
  <% @book.post_comments.each do |post_comment| %>
    <li class="comments_area">
      <div class="comment-body bb">
        <div class="comment-avatar">
          <div class="avatar">
            <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50' %>
          </div>
        </div>
        <div class="comment-text">
          <div class="comment-author clearfix">
            <a href="#" class="link-author"><%= post_comment.user.name %></a>
            <span class="comment-meta">
              <span class="comment-date"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
            </span>
          </div>
          <div class="comment-entry"><%= post_comment.comment %></div>
        </div>
        <% if post_comment.user == current_user %>
          <%= link_to "destroy", book_post_comment_path(post_comment.book, post_comment), method: :delete, class: "btn-sm btn-danger pull-right", remote: true %>
        <% end %>
      </div>
    </li>
  <% end %>
</ol>

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <%= notice %> 
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body' %>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<%= render "books/form", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>
</div>

<% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
    	<p>error</p>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/index.html.erb
<div class="container"> 
	<div class="row">
		<div class="col-xs-3">
	
			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
	
			<%= render 'layouts/errors', obj: @book %>
	
			<h2>New book</h2>
			<%= render 'books/form', book: @book %>
	
		</div>
	
		<div class="col-xs-9">
			<h2>Books index</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>
	
				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<td>
		          <div id="favorites_buttons_<%= book.id %>">
		             <%= render partial: 'favorites/favorite', locals: { book: book } %>
		          </div>
						</td>
						<td><%= link_to "#{book.post_comments.count} コメント" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
	
			<!--books一覧 -->
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container"> 
	<div class="row">
		<div class="col-xs-3">
	
			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>
	
			<h2>New book</h2>
			<%= render 'books/form', book: @new_book %>
	
		</div>
	
		<div class="col-xs-9">
			<h2>Book detail</h2>
			<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@user.id) do %>
							<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'100x100' %><br>
						<%= @user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>
					<% if @user.id == current_user.id %>
					<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
		            <% if @book.favorited_by?(current_user) %>
		              <th>
		                <%= link_to book_favorites_path(@book), method: :delete do %>
		                <i><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></i>
		                <%= @book.favorites.count %>
		              </th>
		            <% end %>
		            <% else %>
		              <th>
		                <%= link_to book_favorites_path(@book), method: :post do %>
		                  <i><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></i>
		                  <%= @book.favorites.count %>
		                <% end %>
		              </th>
		            <% end %>
					</td>
					<% end %>
				</tr>
			</table>
			
		    <li>
			  <i class="fa fa-comment"></i>
			  <a href="#comments"><%= @book.post_comments.count %>件のコメント</a>
			</li>

			<div id="comments_area">
			  <%= render partial: 'books/book', locals: { book: @book } %>
	        </div>		
                                 <!-- コメントフォームここから-->
			<%= form_for [@book, @post_comment], remote: true do |f| %>
			<div class="row">
				<div class="col-sm-12">
					<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに記入" %>
				</div>
			</div>
			<%= f.submit "送信", class: "btn btn-sm btn-base-1 mt-20 pull-right" %>
			<% end %>
                                 <!-- コメントフォームここまで-->				
		</div>
	</div>
</div>